apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: etqlmc1kk-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:7f45d6bb75d5d4017fac4e4646410f55f65a5043@sha256:3b3138fd9e1c1a5ddeeec3f14cd25416961063ab42e4f2dd45be896c378fca83
          name: container-image
